//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace glass {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("glass.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap bil_bla {
			get {
				object obj = ResourceManager.GetObject("bil_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap bil_gron {
			get {
				object obj = ResourceManager.GetObject("bil_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap bil_gul {
			get {
				object obj = ResourceManager.GetObject("bil_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap bil_rod {
			get {
				object obj = ResourceManager.GetObject("bil_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap bil_vit {
			get {
				object obj = ResourceManager.GetObject("bil_vit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap boll_fotboll {
			get {
				object obj = ResourceManager.GetObject("boll_fotboll", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap button {
			get {
				object obj = ResourceManager.GetObject("button", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap byxa_bla {
			get {
				object obj = ResourceManager.GetObject("byxa_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap byxa_gron {
			get {
				object obj = ResourceManager.GetObject("byxa_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap byxa_gul {
			get {
				object obj = ResourceManager.GetObject("byxa_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap byxa_rod {
			get {
				object obj = ResourceManager.GetObject("byxa_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap camera {
			get {
				object obj = ResourceManager.GetObject("camera", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap done {
			get {
				object obj = ResourceManager.GetObject("done", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap down {
			get {
				object obj = ResourceManager.GetObject("down", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap exit {
			get {
				object obj = ResourceManager.GetObject("exit", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap frukt_apple {
			get {
				object obj = ResourceManager.GetObject("frukt_apple", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap frukt_banan {
			get {
				object obj = ResourceManager.GetObject("frukt_banan", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap frukt_bappelsin {
			get {
				object obj = ResourceManager.GetObject("frukt_bappelsin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap frukt_paron {
			get {
				object obj = ResourceManager.GetObject("frukt_paron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap gubbe {
			get {
				object obj = ResourceManager.GetObject("gubbe", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hus_brun {
			get {
				object obj = ResourceManager.GetObject("hus_brun", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hus_gul {
			get {
				object obj = ResourceManager.GetObject("hus_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hus_rodprick {
			get {
				object obj = ResourceManager.GetObject("hus_rodprick", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hus_rosa {
			get {
				object obj = ResourceManager.GetObject("hus_rosa", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap hus_vitprick {
			get {
				object obj = ResourceManager.GetObject("hus_vitprick", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap jacka_bla {
			get {
				object obj = ResourceManager.GetObject("jacka_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap jacka_gron {
			get {
				object obj = ResourceManager.GetObject("jacka_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap jacka_gul {
			get {
				object obj = ResourceManager.GetObject("jacka_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap jacka_rod {
			get {
				object obj = ResourceManager.GetObject("jacka_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mossa_bla {
			get {
				object obj = ResourceManager.GetObject("mossa_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mossa_gron {
			get {
				object obj = ResourceManager.GetObject("mossa_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mossa_gul {
			get {
				object obj = ResourceManager.GetObject("mossa_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap mossa_rod {
			get {
				object obj = ResourceManager.GetObject("mossa_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap new_user {
			get {
				object obj = ResourceManager.GetObject("new_user", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap plate {
			get {
				object obj = ResourceManager.GetObject("plate", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap rum_frukter {
			get {
				object obj = ResourceManager.GetObject("rum_frukter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap rum_klader {
			get {
				object obj = ResourceManager.GetObject("rum_klader", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap rum_prepositioner {
			get {
				object obj = ResourceManager.GetObject("rum_prepositioner", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap strumpa_bla {
			get {
				object obj = ResourceManager.GetObject("strumpa_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap strumpa_gron {
			get {
				object obj = ResourceManager.GetObject("strumpa_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap strumpa_gul {
			get {
				object obj = ResourceManager.GetObject("strumpa_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap strumpa_rod {
			get {
				object obj = ResourceManager.GetObject("strumpa_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap t_bla {
			get {
				object obj = ResourceManager.GetObject("t_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap t_gron {
			get {
				object obj = ResourceManager.GetObject("t_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap t_gul {
			get {
				object obj = ResourceManager.GetObject("t_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap t_rod {
			get {
				object obj = ResourceManager.GetObject("t_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap troja_bla {
			get {
				object obj = ResourceManager.GetObject("troja_bla", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap troja_gron {
			get {
				object obj = ResourceManager.GetObject("troja_gron", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap troja_gul {
			get {
				object obj = ResourceManager.GetObject("troja_gul", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap troja_rod {
			get {
				object obj = ResourceManager.GetObject("troja_rod", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap up {
			get {
				object obj = ResourceManager.GetObject("up", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
